### ISSUE TITLE
Make use of <testcase status-id="approved"> to update Test Case status

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#107]
Please add support to identify the test case status and make use of `<testcase status-id="approved">` to update it accordingly when generating the import XML for test cases.

**Comment by elyezer** [comment]
Current WIP branch is available at https://github.com/SatelliteQE/betelgeuse/compare/issues/107.

In addition to the `status-id` attribute, there is also  the `approver-ids`. I think both need to be set in order to properly approve a test case but I don't have the confirmation yet. As soon as I confirm that I am going to update the changes (if needed) and get them merged.
