### ISSUE TITLE
"betelgeuse test-run --status inprogress" isnt updating the test-run correctly

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/betelgeuse#130]
Running `betelgeuse test-run --status inprogress` runs and includes `<property name="polarion-set-testrun-finished" value="false" />` in the importer xml but when importer imports the xml, the test run changes the state to `Finished`.

Please look into it.

As per the last discussion with @elyezer, Polarion have changed the property to `polarion-testrun-status-id`.

**Comment by mshriver** [comment]
I think this fix is incomplete at this point, as the XML needs to actually have the testrun status as a string value in the attribute, like `<property name="polarion-testrun-status-id" value="inprogress"/>`. The update in #131 will set `<property name="polarion-testrun-status-id" value="true"/>` since its still comparing to expected strings and setting a boolean.

**Comment by elyezer** [comment]
That is correct @mshriver, I've merged the PR because the tests needed some love and linter was failing. I will get everything updated soon.

**Comment by elyezer** [comment]
Updates are now in, see https://github.com/SatelliteQE/betelgeuse/commit/2fd5377e726a79604dc4100443a65b4bf11c947c
