### ISSUE TITLE
RFE :: Steps should go in Test Steps and Assert should go in expected result.

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#38]
Betelgeuse is currently taking the docstring from test cases and putting that into the description field of Polarion. It will be nice if all the information in docstring can go to the specific field ::

For Example :

@Feature: Replication

@Setup: Four masters, replication is configured

@Steps:
1. Install four instances of Directory Server on same host i.e. M1, M2, M3, M4
2. Configure two way replcation between all instances.
3. Add a test user in M1.
4. Verify all the masters M2, M3 and M4 have that test user added.

@Assert: All masters should be in sync.

@Status: Manual

Steps should go in Test Steps and Assert should go in expected result.

**Comment by Akasurde** [comment]
+1

**Comment by elyezer** [comment]
This will require some design decision because each test step have an expected result in Polarion.

My idea on solving this is:

Expect a list for steps and a list for assert. Then each element of one list will mapped to the same index of the other list (example 1). If it is a single item, then there is no need to use the list syntax (example 2). If neither of the mentioned is found then step's content will go to the first step, and the content of assert will go to the first step expected condition, for example, if number of items on both lists don't match or if parsing the tokens' content fail.  

Example 1:

``` python
"""My test

@steps:

1. First step
2. Second step
3. Third step

@assert:

1. First step expected condition.
2. Second step expected condition.
3. Third step expected condition.
"""
```

Example 2:

``` python
"""My test case

@steps:

Single step

@assert:

Single step expected condition.
""""
```

We should probably rename `assert` to `expectedresults` to have a better meaning.

**Comment by Akasurde** [comment]
@elyezer What if we have example something like this, 

```
"""
My test case 

@steps:
1. First Step
2. Second Step
3. Third Step

@assert:
1. Final result
"""
```

+1 for renaming `expectedresults`

**Comment by elyezer** [comment]
@Akasurde that will generate one step with the content of:

```
1. First Step
2. Second Step
3. Third Step
```

And the expected result of:

```
1. Final result
```

The render on Polarion will be something like

<table>
<tr>
  <td>Step 1</td>
  <td><ol><li>First Step</li><li>Second Step</li><li>Third Step</li></td>
  <td><ol><li>Final result</li></ol></td></tr>
</table>
