### ISSUE TITLE
 Warning message is also added in that particular section along with text.

### ISSUE THREAD

**Issue by madhuriupadhye** [SatelliteQE/betelgeuse#52]
Suppose after running the .py file contains some warning like (WARNING/2) Enumerated list ends without a blank line; unexpected unindent for steps section then it was added in steps section of polarion with steps.
![screenshot from 2016-07-07 12 10 26](https://cloud.githubusercontent.com/assets/18697962/16644663/481f5ff8-443c-11e6-8b27-2d53c2c8bbeb.png)

**Comment by elyezer** [comment]
@madhuriupadhye thank you for creating the issue. Make sure you have the valid Restructured Text before running Betelgeuse. I think it is able to remove that warning, but having that makes us aware that our RST formatting is not good.

I've been thinking on a way to fix it, but I have not decided what is best, skip the test case if the parse can't be successfully completed (which is bad because that is not a blocker for creating the test case), just remove the warning and have poorly formatted information on Polarion (by removing the warning you will end up with a list of 3 elements and one paragraph starting with the literal string `4.` on your example).  With that said I don't see any other option and I think is better to have the warning so we can update the docstring to make it able to be parsed properly.

**Comment by elyezer** [comment]
Removing the bug label since this is not a Betelgeuse bug but a feature to notify when bad RST docstring is received.

**Comment by sthirugn** [comment]
@madhuriupadhye can you paste the test docstring test case which created this error?

**Comment by elyezer** [comment]
The issue is mostly like because the second line of item 4 was not indented, it should be like this:

```
4. first line
line continuation
```

While it should be something like:

```
4. first line
   line continuation
```

**Comment by elyezer** [comment]
I can't reproduce this with the latest version of Betelgeuse.
