### ISSUE TITLE
Improve docs on default values and minimum tokens

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/betelgeuse#55]
https://github.com/SatelliteQE/betelgeuse/pull/53#discussion_r70012644

**Comment by sthirugn** [comment]
@elyezer: This is already addressed in testimony - http://testimony-qe.readthedocs.io/en/latest/#test-case-docstring-format  Do you think we need more doc?

**Comment by elyezer** [comment]
@sthirugn I think we should add a section to the betelgeuse documentation saying what are the fields it will be looking for populate Polarion. I think that because betelgeuse have it's own expected tokens and we should let the user know what the tokens are.

This will help the user identify when some information is not being captured, it could be a misspell or an invalid token defined.

**Comment by elyezer** [comment]
The default Betelgeuse configuration provides the values for the fields. All that is presented by this section in the docs https://betelgeuse.readthedocs.io/en/latest/config.html#default-configuration, so we can go ahead and close this one.
